#!/bin/bash
#SBATCH -J topk
#SBATCH -p cas_v100_4
#SBATCH -N 2
#SBATCH -n 2
#SBATCH -o %x.o%j
#SBATCH -e %x.e%j
#SBATCH --time 02:00:00
#SBATCH --gres=gpu:1
#SBATCH --comment etc     # See Application SBATCH options name table's

module purge
module load python/3.7.1
source activate sage

nodes=( $( scontrol show hostnames $SLURM_JOB_NODELIST ) )
nodes_array=($nodes)
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

echo Node IP: $head_node_ip
export LOGLEVEL=INFO

hostip=$head_node_ip srun run.sh
#srun torchrun --rdzv_id $RANDOM --rdzv_backend=distributed_backend --rdzv_endpoint=$head_node_ip:29500 --nnodes=2 --nproc_per_node=1 a.py
